# -*- mode: ruby -*-
# vi: set ft=ruby :


servers=[
  {
	:hostname => "kube1.gokul.com",
	:box => "gokulc/CentOS_7",
	:cpu => 1,
	:ram => 2048,
	:ip => "192.168.56.60",
  },
]
Vagrant.configure("2") do |config|
	config.vm.box = "gokulc/CentOS_7"
	servers.each do |machine|
		config.vm.define machine[:hostname] do |node|
			node.vm.box = machine[:box]
			node.vm.hostname = machine[:hostname]
			node.vm.network "public_network"
			node.vm.network "private_network", ip: machine[:ip]
			node.vm.provider "virtualbox" do |vb|
				vb.customize ["modifyvm", :id, "--memory", machine[:ram], "--cpus", machine[:cpu]]
			end
		end
	end
end
