# -*- mode: ruby -*-
# vi: set ft=ruby :


servers=[
  {
	:hostname => "kube1.gokul.com",
	:box => "gokulc/kubernetes2",
	:cpu => 1,
	:ram => 8096,
  },
  {
	:hostname => "kube2.gokul.com",
	:box => "gokulc/kubernetes2",
	:cpu => 1,
	:ram => 8096,
  },
  {
	:hostname => "kube3.gokul.com",
	:box => "gokulc/kubernetes2",
	:cpu => 1,
	:ram => 8096,
  },
  {
	:hostname => "kube4.gokul.com",
	:box => "gokulc/kubernetes2",
	:cpu => 1,
	:ram => 8096,
  },
  {
	:hostname => "kube5.gokul.com",
	:box => "gokulc/kubernetes2",
	:cpu => 1,
	:ram => 8096,
  }
]
Vagrant.configure("2") do |config|
	servers.each do |machine|
		config.vm.define machine[:hostname] do |node|
			node.vm.box = machine[:box]
			node.vm.hostname = machine[:hostname]
			node.vm.network "public_network"
			node.vm.provision "shell",
				run: "always",
				inline: "sudo route add default gw 192.168.1.1 && sudo sh -c 'echo GATEWAY=192.168.1.1 >> /etc/sysconfig/network && echo GATEWAYDEV=enp0s8 >> /etc/sysconfig/network'"
			node.vm.provider "virtualbox" do |vb|
				vb.customize ["modifyvm", :id, "--memory", machine[:ram], "--cpus", machine[:cpu]]
			end
		end
	end
end
